# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/martin/devbot/mmbot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/martin/devbot/mmbot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/martin/devbot/mmbot/CMakeFiles /home/martin/devbot/mmbot/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/martin/devbot/mmbot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named imtjson

# Build rule for target.
imtjson: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imtjson
.PHONY : imtjson

# fast build rule for target.
imtjson/fast:
	$(MAKE) -f src/imtjson/src/imtjson/CMakeFiles/imtjson.dir/build.make src/imtjson/src/imtjson/CMakeFiles/imtjson.dir/build
.PHONY : imtjson/fast

#=============================================================================
# Target rules for targets named simpleServer

# Build rule for target.
simpleServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simpleServer
.PHONY : simpleServer

# fast build rule for target.
simpleServer/fast:
	$(MAKE) -f src/server/src/simpleServer/CMakeFiles/simpleServer.dir/build.make src/server/src/simpleServer/CMakeFiles/simpleServer.dir/build
.PHONY : simpleServer/fast

#=============================================================================
# Target rules for targets named brokers_common

# Build rule for target.
brokers_common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 brokers_common
.PHONY : brokers_common

# fast build rule for target.
brokers_common/fast:
	$(MAKE) -f src/brokers/CMakeFiles/brokers_common.dir/build.make src/brokers/CMakeFiles/brokers_common.dir/build
.PHONY : brokers_common/fast

#=============================================================================
# Target rules for targets named mmbot

# Build rule for target.
mmbot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mmbot
.PHONY : mmbot

# fast build rule for target.
mmbot/fast:
	$(MAKE) -f src/main/CMakeFiles/mmbot.dir/build.make src/main/CMakeFiles/mmbot.dir/build
.PHONY : mmbot/fast

#=============================================================================
# Target rules for targets named binance

# Build rule for target.
binance: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 binance
.PHONY : binance

# fast build rule for target.
binance/fast:
	$(MAKE) -f src/binance/CMakeFiles/binance.dir/build.make src/binance/CMakeFiles/binance.dir/build
.PHONY : binance/fast

#=============================================================================
# Target rules for targets named bitmex

# Build rule for target.
bitmex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bitmex
.PHONY : bitmex

# fast build rule for target.
bitmex/fast:
	$(MAKE) -f src/bitmex/CMakeFiles/bitmex.dir/build.make src/bitmex/CMakeFiles/bitmex.dir/build
.PHONY : bitmex/fast

#=============================================================================
# Target rules for targets named coinbase

# Build rule for target.
coinbase: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coinbase
.PHONY : coinbase

# fast build rule for target.
coinbase/fast:
	$(MAKE) -f src/coinbase/CMakeFiles/coinbase.dir/build.make src/coinbase/CMakeFiles/coinbase.dir/build
.PHONY : coinbase/fast

#=============================================================================
# Target rules for targets named coingi

# Build rule for target.
coingi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coingi
.PHONY : coingi

# fast build rule for target.
coingi/fast:
	$(MAKE) -f src/coingi/CMakeFiles/coingi.dir/build.make src/coingi/CMakeFiles/coingi.dir/build
.PHONY : coingi/fast

#=============================================================================
# Target rules for targets named coinmate

# Build rule for target.
coinmate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coinmate
.PHONY : coinmate

# fast build rule for target.
coinmate/fast:
	$(MAKE) -f src/coinmate/CMakeFiles/coinmate.dir/build.make src/coinmate/CMakeFiles/coinmate.dir/build
.PHONY : coinmate/fast

#=============================================================================
# Target rules for targets named deribit

# Build rule for target.
deribit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deribit
.PHONY : deribit

# fast build rule for target.
deribit/fast:
	$(MAKE) -f src/deribit/CMakeFiles/deribit.dir/build.make src/deribit/CMakeFiles/deribit.dir/build
.PHONY : deribit/fast

#=============================================================================
# Target rules for targets named poloniex

# Build rule for target.
poloniex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 poloniex
.PHONY : poloniex

# fast build rule for target.
poloniex/fast:
	$(MAKE) -f src/poloniex/CMakeFiles/poloniex.dir/build.make src/poloniex/CMakeFiles/poloniex.dir/build
.PHONY : poloniex/fast

#=============================================================================
# Target rules for targets named simplefx

# Build rule for target.
simplefx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simplefx
.PHONY : simplefx

# fast build rule for target.
simplefx/fast:
	$(MAKE) -f src/simplefx/CMakeFiles/simplefx.dir/build.make src/simplefx/CMakeFiles/simplefx.dir/build
.PHONY : simplefx/fast

#=============================================================================
# Target rules for targets named trainer

# Build rule for target.
trainer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trainer
.PHONY : trainer

# fast build rule for target.
trainer/fast:
	$(MAKE) -f src/trainer/CMakeFiles/trainer.dir/build.make src/trainer/CMakeFiles/trainer.dir/build
.PHONY : trainer/fast

#=============================================================================
# Target rules for targets named report_broker

# Build rule for target.
report_broker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 report_broker
.PHONY : report_broker

# fast build rule for target.
report_broker/fast:
	$(MAKE) -f src/report_broker/CMakeFiles/report_broker.dir/build.make src/report_broker/CMakeFiles/report_broker.dir/build
.PHONY : report_broker/fast

#=============================================================================
# Target rules for targets named storage_broker

# Build rule for target.
storage_broker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 storage_broker
.PHONY : storage_broker

# fast build rule for target.
storage_broker/fast:
	$(MAKE) -f src/storage_broker/CMakeFiles/storage_broker.dir/build.make src/storage_broker/CMakeFiles/storage_broker.dir/build
.PHONY : storage_broker/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... imtjson"
	@echo "... simpleServer"
	@echo "... brokers_common"
	@echo "... mmbot"
	@echo "... binance"
	@echo "... bitmex"
	@echo "... coinbase"
	@echo "... coingi"
	@echo "... coinmate"
	@echo "... deribit"
	@echo "... poloniex"
	@echo "... simplefx"
	@echo "... trainer"
	@echo "... report_broker"
	@echo "... storage_broker"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

